version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "io.netty:*"
      - dependency-name: "com.fasterxml.jackson.core:*"
      - dependency-name: "com.fasterxml.jackson.module:*"
    ignore:
      # Allow only patch updates for Netty
      - dependency-name: "io.netty:*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: "maven"
    directory: "/core-io-deps"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "io.netty:*"
      - dependency-name: "com.fasterxml.jackson.core:*"
      - dependency-name: "com.fasterxml.jackson.module:*"
    ignore:
      # Allow only patch updates for Netty
      - dependency-name: "io.netty:*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
