= How to Write Javadoc

[abstract]
A brief guide for style and content.

== Guiding principles

Javadoc comments should render correctly in a web browser.

Avoid excessive markup.
Strike a balance between readable comments in the source code and nicely rendered Javadoc reference material.


== Initial sentence

The first sentence of a Javadoc comment should briefly summarize the behavior/purpose of the class, method, or field.
Write it in the third person, as if it began with "This class/method/field".

.Example:
```java
/**
 * Calculates the discrete cosine transform.
 */
```

== Paragraphs

Use standalone `<p>` tags to separate paragraphs.

.Example:
```java
/**
 * First paragraph.
 * <p>
 * Second paragraph.
 */
```

== Inline tags

=== link

Use the `{@link}` inline tag the first time a linkable program element is referenced in a Javadoc comment.
Don't link subsequent references; instead, mark them with the `{@code}` inline tag.
Don't link common classes such as boxed primitives, `String`, `List`, `Set`, `Map`, etc.


=== code

Use the `{@code}` inline tag to mark up literal phrases, except for the simple literals `true`, `false`, and `null` which should not be marked up.


=== inheritDoc

Use the `{@inheritDoc}` inline tag only if additional documentation is present.
It should never be the sole content of a Javadoc comment.


== Code samples

Enclose multi-line code samples and other pre-formatted texts (such as ASCII-art tables) in `<pre>` & `</pre>` tag pairs.

.Example:
```java
/**
 * Sample usage:
 * <pre>
 * int foo = someMethod();
 * int bar = someOtherMethod(foo);
 * </pre>
 */
```

== Lists

Express lists using `<ol>` or `<ul>` tag pairs.
Omit closing `<li`> tags.

.Example:
```java
/**
 * <ol>
 * <li>It's just a jump to the left
 * <li>And then a step to the right
 * </ol>
 */
```

== Asynchronous exceptions

For methods returning `CompletableFuture`, `Flux`, or `Mono`, use the `@throws` tag for each exception expected to be thrown asynchronously.
Prefix the description of an asynchronous exception with "(async) ".

.Example:
```java
/**
 * Asynchronously perform all tasks for a given day of the week.
 *
 * @param dayOfWeek integer in the range [0,6] where 0 = Monday
 * @throws IllegalArgumentException if dayOfWeek is outside valid range
 * @throws TaskFailedException (async) if async processing fails
 */
```

== Nullability

If null is a valid value for a parameter or return value, the description should include a statement of how a null parameter is interpreted, or under what circumstances null is returned.

.Example:
```java
/**
 * @param foo If null, the global default is used instead.
 * @returns Something or other, or null if the given foo is null and there is no global default.
 */
```
