= Absent Value Guidelines for Java

[abstract]
Tips for dealing with absent values in a consistent way.

== @Nullable annotation

All fields, parameters, and return values that allow null should be annotated with `@org.jspecify.annotations.Nullable`.
Put the annotation as close to the type as possible.

Fields, parameters, and return values are assumed non-nullable by default.
When creating a new package, consider making this explicit by adding a `package-info.java` and annotating the package with `@org.specify.annotations.NullMarked`.

For more information, see https://jspecify.dev[JSpecify].

Here's an example of how to annotate nullable fields, parameters, and return values.
Pay special attention to the byte array field.

[source,java]
----
@NullMarked // <1>
public class GoodExample {
  private final String id;
  private final @Nullable String name;
  private final byte @Nullable [] nameBytes; // <2>

  public GoodExample(String id, @Nullable String name) {
    this.id = requireNonNull(id);
    this.name = name;
    this.nameBytes = name == null ? null : name.getBytes(UTF_8);
  }

  public String getId() {
    return id;
  }

  public @Nullable String getName() {
    return name;
  }

  public byte @Nullable [] getNameBytes() {
    return nameBytes;
  }

  public static List<@Nullable String> getNames(List<GoodExample> items) {
    return items.stream()
      .map(GoodExample::getName)
      .collect(toList());
  }
}
----
<1> If possible, use a `package-info.java` file to annotate the whole package as `@NullMarked` instead of annotating individual classes.
<2> It might look strange at first, but this is how JSpecify wants us to annotate a nullable array of non-null elements.
In other words, the reference to the array is nullable, but elements of the array are not.
See https://jspecify.dev/docs/user-guide/#type-use-annotation-syntax[JSpecify type-use annotation syntax].

== Container Types

Follow Joshua Bloch's advice from Effective Java, Item 43: "Return empty arrays or collections, not nulls."

For List, Set, Map, etc. use an empty container to represent an absent value.
In the rare case you must distinguish between an empty container and an absent value, follow the guideline for "other" types.

== User-Defined Types

Consider using the https://en.wikipedia.org/wiki/Null_object_pattern[Null Object Pattern], where a special instance represents an absent value.
Otherwise, follow the guidelines for "other" types.

NOTE: The Null Object Pattern reduces the https://en.wikipedia.org/wiki/Cyclomatic_complexity[cyclomatic complexity] of your code.
In other words, your code needs fewer branches.

== Other Types

=== As a parameter

Annotate with `@Nullable`.

Using `Optional` as a parameter type is discouraged because it forces the caller to write verbose code, and does not prevent callers from accidentally passing null.

=== As a return value

In the public API, prefer Optional.

The public API is how we communicate with users.
Optional is a clear, impossible-to-ignore signal that the return value might be absent.
When used as a return value, Optional is primarily a tool for communication.

In the internal API, use Optional or @Nullable at your discretion.

Methods at component boundaries might use Optional to more clearly advertise their behavior to other components.

Optional can be overkill when communicating with yourself, as when calling private methods.
Nulls are less dangerous when confined to a small scope, like the internals of a component or a single class.

=== As a field

Prefer @Nullable, unless Optional offers a clear advantage.

For example, if a field is used exclusively by an accessor that returns Optional, it's reasonable for the field to be an Optional, so the accessor doesn't need to create a new Optional on every call.

Note that any class ultimately accessed by the Couchbase Spark Connector needs to implement Serializable, and Optional is not Serializable.
This will apply to any class in core-io that is ultimately in a Scala SDK object being returned to the user.

References:

* https://issues.couchbase.com/browse/JVMCBC-1458[JVMCBC-1458]
* https://stackoverflow.com/questions/24547673/why-java-util-optional-is-not-serializable-how-to-serialize-the-object-with-suc/24564612#24564612[StackOverflow post]

== Constructors

Constructors should verify that parameters not annotated as @Nullable are actually non-null.
A simple `requireNonNull(foo)` is sufficient.
This is a "comment with teeth", not something we expect to happen; a fancy message is not required.
