name: Maven Deploy Snapshot

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - master
      - 3.9.x
    paths-ignore:
      - '.gitignore'
      - '.editorconfig'
      - '.scalafmt.conf'
      - '*-fit-*/**'
      - '*-examples/**'
      - 'test-utils/**'
      - 'Jenkinsfile'
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

          server-id: 'central'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

          cache: 'maven'

      - name: Build and deploy to Maven Central
        run: .github/scripts/deploy.sh snapshot
        env:
          MAVEN_USERNAME: ${{ vars.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_KEY: ${{ secrets.SDK_ROBOT_GPG_PRIVATE_KEY }}
          MAVEN_GPG_PASSPHRASE: ''

      - name: Remove artifacts from Maven repo so they're not cached
        run: rm -rfv ~/.m2/repository/com/couchbase/client/
